[tool.poetry]
name = "dmc-docs"
version = "0.1.0"
description = "Official documentation for Dash Mantine Components library. This documentation is entirely created using components from dash-mantine-components."
authors = ["Snehil Vijay <snehilvj@outlook.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
dash = "^2.0.0"
dash-iconify = "^0.1.0"
mistune = "^2.0.2"
gunicorn = "^20.1.0"
requests = "^2.27.1"
pydantic = "^1.9.0"
python-frontmatter = "^1.0.0"
dash-extensions = "^0.1.0"
pandas = "^1.4.2"
dash-mantine-components = "0.11.0a2"

[tool.poetry.dev-dependencies]
black = "22.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
